/**
 * Created by Zmote on 26.10.2017.
 */
export class GalleryConstants {
  // TODO: Check if baseHref even needed, the backslash less syntax might be enough for auto-resolve of links
  static readonly baseHref = 'assets/img/';

  static readonly threeDImageArray = [
    GalleryConstants.baseHref + '3dgallery/vehicle_02_design_by_zmote-d6tzun5.jpg',
    GalleryConstants.baseHref + '3dgallery/kervansaray_design001.jpg',
    GalleryConstants.baseHref + '3dgallery/architecture.jpg',
    GalleryConstants.baseHref + '3dgallery/cargo_ship_by_zmote-d6p1ugd.jpg',
    GalleryConstants.baseHref + '3dgallery/city_of_winterburg__final_layout_by_zmote-d6pzdzu.jpg',
    GalleryConstants.baseHref + '3dgallery/clientwork_cam_model_preview_by_zmote-d5m7yu0.jpg',
    GalleryConstants.baseHref + '3dgallery/dat_face_by_zmote-daadprp.jpg',
    GalleryConstants.baseHref + '3dgallery/medieval_hostel__with_solar_panels_by_zmote-d79iekf.jpg',
    GalleryConstants.baseHref + '3dgallery/rensei_ruin___unknown_nameless___design_001_by_zmote-da8ikxr.jpg',
    GalleryConstants.baseHref + '3dgallery/survey_copter_by_zmote-d78gnav.jpg',
    GalleryConstants.baseHref + '3dgallery/wacom_intuos5_model_tribute_by_z_mote-d56co5v.jpg',
    GalleryConstants.baseHref + '3dgallery/the_barrel_inn_by_zmote-d7g24kx.png',
    GalleryConstants.baseHref + '3dgallery/caylarrrrr_by_z_mote-d499mx4.png'];

  static readonly twoDImageArray = [
    GalleryConstants.baseHref + '2dgallery/a_purposeful_meeting____by_zmote-d75n3tb.jpg',
    GalleryConstants.baseHref + '2dgallery/arriving_in_a_strange_world_by_zmote-d6kl0yj.jpg',
    GalleryConstants.baseHref + '2dgallery/color_sketch_004i_by_zmote-d66shah.jpg',
    GalleryConstants.baseHref + '2dgallery/cuneyt_arkin_by_z_mote-d5dpyt6.jpg',
    GalleryConstants.baseHref + '2dgallery/el_presidente_by_zmote-dbj89t6.png',
    GalleryConstants.baseHref + '2dgallery/for_funz_by_zmote-d6kcnld.jpg',
    GalleryConstants.baseHref + '2dgallery/material_study_005_by_zmote-d6bpklj.jpg',
    GalleryConstants.baseHref + '2dgallery/winterburg_fountain_final_by_zmote-d6rcq79.jpg',
    GalleryConstants.baseHref + '2dgallery/winterburg_marketscene_final_by_zmote-d6vurgd.jpg',
    GalleryConstants.baseHref + '2dgallery/world_of_seyyare___entire_map__full_resolution_by_zmote-d6qfu09.jpg'];

  static readonly conceptImageArray = [
    GalleryConstants.baseHref + 'concept/001.jpg',
    GalleryConstants.baseHref + 'concept/30_30_costume_design_sketches____by_zmote-d6t0wp3.jpg',
    GalleryConstants.baseHref + 'concept/arriving_at_narufo___scene_concept_by_zmote-da8m9ak.jpg',
    GalleryConstants.baseHref + 'concept/Bild004.jpg',
    GalleryConstants.baseHref + 'concept/caricature_sketch_001.jpg',
    GalleryConstants.baseHref + 'concept/colorSketchv1.jpg',
    GalleryConstants.baseHref + 'concept/compositional_experiment___pictorial_compsotion_00_by_zmote-da9o4fu.jpg',
    GalleryConstants.baseHref + 'concept/compositional_experiments_by_zmote-da9639e.jpg',
    GalleryConstants.baseHref + 'concept/imaginary_piece_019_by_zmote-d681a0m.jpg',
    GalleryConstants.baseHref + 'concept/imaginary_piece_020_by_zmote-d681sm4.jpg',
    GalleryConstants.baseHref + 'concept/inktober__010_by_zmote-dbq8bg8.jpg',
    GalleryConstants.baseHref + 'concept/lineart_for_contest_corkya_by_zmote-d5k1sx9.jpg',
    GalleryConstants.baseHref + 'concept/logoprototypesheets.jpg',
    GalleryConstants.baseHref + 'concept/n_waves_logo_design_sketches_by_zmote-dbrbjbj.jpg',
    GalleryConstants.baseHref + 'concept/quick_scene_sketch_by_zmote-dbl8gox.jpg',
    GalleryConstants.baseHref + 'concept/scene_sketch_004_by_zmote-dbrdmks.jpg',
    GalleryConstants.baseHref + 'concept/scene_sketch_007_by_zmote-dblb53y.jpg',
    GalleryConstants.baseHref + 'concept/scene_wip_001___world_building_course_by_zmote-d6u402d.jpg',
    GalleryConstants.baseHref + 'concept/some_ship_by_zmote-dbqu6zv.jpg',
    GalleryConstants.baseHref + 'concept/the_longing___a_quick_concept_by_zmote-da8mz2g.jpg',
    GalleryConstants.baseHref + 'concept/united_we_stand_divided_we_fall_wip_by_zmote-d6i583a.jpg',
    GalleryConstants.baseHref + 'concept/Unti3tled-1.jpg',
    GalleryConstants.baseHref + 'concept/vehicle_final____by_zmote-d6tw8uz.jpg',
    GalleryConstants.baseHref + 'concept/week_04___clothing_sketches____by_zmote-d6spqr2.jpg',
    GalleryConstants.baseHref + 'concept/week_10_thumbnail_batches____first_6_out_of_200_xd_by_zmote-d6enp2q.jpg',
    GalleryConstants.baseHref + 'concept/wip___journey_on_a_whale_by_zmote-da8w8s7.jpg',
    GalleryConstants.baseHref + 'concept/wip_sketch_001_out_of_the_woods_by_zmote-d98bou0.jpg'];

  static readonly designImageArray = [
    GalleryConstants.baseHref + 'designs/57a945bb69a58de2c4da952e0ff8af95-d68yzcu.png',
    GalleryConstants.baseHref + 'designs/alienOnWatch.jpg',
    GalleryConstants.baseHref + 'designs/bersichtimageware_by_zmote-d5t47tr.png',
    GalleryConstants.baseHref + 'designs/BestelineLogo.JPG',
    GalleryConstants.baseHref + 'designs/brotherlogo_by_zmote-d5t47b7.png',
    GalleryConstants.baseHref + 'designs/cemilabisample-08.png',
    GalleryConstants.baseHref + 'designs/color_composition_by_zmote-d5s17oj.jpg',
    GalleryConstants.baseHref + 'designs/computerdesign_by_zmote-d5t4819.png',
    GalleryConstants.baseHref + 'designs/designwork_002_by_z_mote-d5cgn2y.jpg',
    GalleryConstants.baseHref + 'designs/designwork_003_by_z_mote-d5cgnb8.jpg',
    GalleryConstants.baseHref + 'designs/designwork_010_by_z_mote-d5fn5j4.jpg',
    GalleryConstants.baseHref + 'designs/Ekol_kids_Flyer_a5_front.jpg',
    GalleryConstants.baseHref + 'designs/ekolFrühanmeldung_frontDEUTSCHCMYKPRINTREADYA4.jpg',
    GalleryConstants.baseHref + 'designs/EliteFlyer_front_CMYK_mitBescnittzugabe1mm.jpg',
    GalleryConstants.baseHref + 'designs/erdal_bakkal_by_zmote-d5qijdr.jpg',
    GalleryConstants.baseHref + 'designs/flyerA4RGB.jpg',
    GalleryConstants.baseHref + 'designs/geleneksel_tanisma_cayi_2013_by_zmote-d5vu12a.jpg',
    GalleryConstants.baseHref + 'designs/iftar-flyer-simple-v4.jpg',
    GalleryConstants.baseHref + 'designs/iftar-flyer-v3.jpg',
    GalleryConstants.baseHref + 'designs/ITClub_fuer_Damen.jpg',
    GalleryConstants.baseHref + 'designs/iw3dwithreflection_by_zmote-d5t47ok.png',
    GalleryConstants.baseHref + 'designs/kermes2013_by_zmote-d608dab.jpg',
    GalleryConstants.baseHref + 'designs/logofinal.jpg',
    GalleryConstants.baseHref + 'designs/Mehmet Dogan pm2world Visitenkarte.jpg',
    GalleryConstants.baseHref + 'designs/MPM GmbH Logo Neu ok.jpg',
    GalleryConstants.baseHref + 'designs/new_facebook_avatar_by_zmote-dborjiz.jpg',
    GalleryConstants.baseHref + 'designs/Oberuzwil Pinocchip 4-Seitig PDF-1.jpg',
    GalleryConstants.baseHref + 'designs/pinochio_back.jpg',
    GalleryConstants.baseHref + 'designs/pinochio_front.jpg',
    GalleryConstants.baseHref + 'designs/rejected_logo_desgns____by_zmote-d5xkz9m.jpg',
    GalleryConstants.baseHref + 'designs/some_icon_designs_by_zmote-dazfkq1.jpg',
    GalleryConstants.baseHref + 'designs/some_inbetween_design_work_by_zmote-d6oamv8.jpg',
    GalleryConstants.baseHref + 'designs/säntis.jpg',
    GalleryConstants.baseHref + 'designs/tomateKurierIcon2.jpg',
    GalleryConstants.baseHref + 'designs/tomateKurierIcon3D.jpg',
    GalleryConstants.baseHref + 'designs/wanna_be_friends__by_zmote-d5rypzq.jpg'];
}
